### ISSUE TITLE
Add Soundcloud login service

### ISSUE THREAD

**Issue by ulerch** [lirbank/meteor-accounts-merge#17]
I need the accounts merge for the soundcloud login service. In my local environment I have made the following changes:

file 'accounts-merge-server.js':
- _services = [ "facebook", "twitter", "google", "linkedin", "github" ];
+ _services = [ "facebook", "twitter", "google", "linkedin", "github", "soundcloud" ];

file 'accounts-merge-client.js':
+ Meteor.signInWithSoundcloud = function (options, callback) {
+  Meteor.signInWithExternalService ('loginWithSoundcloud', options, callback);
+};

I tested it and it worked like a charm. Could you please add these changes to the master branch? Thank you in advance.

**Comment by lirbank** [comment]
Arbitrary login services are supported without code changes as of v0.0.9.
