### ISSUE TITLE
Allow arbitrary services

### ISSUE THREAD

**Issue by jamesdwilson** [lirbank/meteor-accounts-merge#23]
I'd like the ability to request arbitrary services such as in my case, quickbooks.

https://github.com/andylash/accounts-quickbooks

**Comment by jamesdwilson** [comment]
This seems to fix it

**Comment by lirbank** [comment]
Great! A new version should be released shortly!

**Comment by lirbank** [comment]
I believe this was resolved with https://github.com/lirbank/meteor-accounts-merge/commit/3b604a6a9c23c624ba89a8a7e0dd11b6b05e764e so closing the issue for now.
