### ISSUE TITLE
Profile name

### ISSUE THREAD

**Issue by ulerch** [lirbank/meteor-accounts-merge#25]
The merge overwrites the profile name of the winner with the loser's name. In my opinion, the name of the winner should only be updated when it is empty.

**Comment by lirbank** [comment]
Agree, happy to accept a pull request.

**Comment by ulerch** [comment]
Pull request is ready since about three weeks. Is there an issue with it or are you just busy?

**Comment by lirbank** [comment]
Sorry, just been busy. Thanks for the reminder, will merge it tomorrow.
Happy Halloween!

**Comment by lirbank** [comment]
Version 0.0.11 is out https://atmospherejs.com/mikael/accounts-merge.

Thanks a lot for the help, appreciate it a lot!
